# Generated by Django 4.2.29 on 2026-04-01 13:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DailyEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_date', models.DateField()),
                ('kind', models.CharField(choices=[('plan', 'Plan'), ('update', 'Update')], max_length=12)),
                ('status', models.CharField(choices=[('open', 'Open'), ('in_progress', 'In Progress'), ('blocked', 'Blocked'), ('closed', 'Closed')], default='open', max_length=16)),
                ('raw_text', models.TextField(blank=True, null=True)),
                ('source', models.CharField(default='web', max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-entry_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(max_length=120, unique=True)),
                ('slack_user_id', models.CharField(blank=True, max_length=64, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['display_name'],
            },
        ),
        migrations.CreateModel(
            name='EntryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_type', models.CharField(max_length=120)),
                ('question_type', models.CharField(blank=True, choices=[('Programming', 'Programming'), ('SQL', 'SQL'), ('Frontend', 'Frontend'), ('Full Stack', 'Full Stack'), ('Automation Testing', 'Automation Testing'), ('DevOps', 'DevOps'), ('Machine Learning', 'Machine Learning'), ('Diagram', 'Diagram'), ('Data Science', 'Data Science'), ('File Upload', 'File Upload'), ('Project', 'Project'), ('Java Project', 'Java Project'), ('C# Project', 'C# Project'), ('Python Project', 'Python Project'), ('Subjective', 'Subjective'), ('Multiple Choice', 'Multiple Choice'), ('Approximate', 'Approximate'), ('Golf', 'Golf'), ('RegExp', 'RegExp'), ('FileEval', 'FileEval')], max_length=120, null=True)),
                ('customer', models.CharField(blank=True, max_length=120, null=True)),
                ('count', models.PositiveIntegerField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='tracker.dailyentry')),
            ],
        ),
        migrations.AddField(
            model_name='dailyentry',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entries', to='tracker.member'),
        ),
        migrations.AddIndex(
            model_name='dailyentry',
            index=models.Index(fields=['entry_date', 'kind'], name='tracker_dai_entry_d_bd3f66_idx'),
        ),
        migrations.AddIndex(
            model_name='dailyentry',
            index=models.Index(fields=['member', 'entry_date'], name='tracker_dai_member__c3afa4_idx'),
        ),
    ]
