# Generated by Django 4.2.29 on 2026-04-06 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyentry',
            name='jira_issue_key',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='dailyentry',
            name='jira_issue_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
