# Generated by Django 4.2.29 on 2026-04-06 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_dailyentry_jira_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='SlackDayThread',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('digest_date', models.DateField()),
                ('kind', models.CharField(max_length=12)),
                ('channel', models.CharField(default='', max_length=120)),
                ('parent_ts', models.CharField(blank=True, help_text='Slack message ts of the parent (thread root)', max_length=32, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='dailyentry',
            name='slack_reply_ts',
            field=models.CharField(blank=True, help_text='Slack ts of thread reply for this entry (if posted)', max_length=32, null=True),
        ),
        migrations.AddConstraint(
            model_name='slackdaythread',
            constraint=models.UniqueConstraint(fields=('digest_date', 'kind'), name='unique_slack_digest_date_kind'),
        ),
    ]
