# Generated by Django 3.2.7 on 2026-04-17 15:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0005_entryitem_due_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='role',
            field=models.CharField(choices=[('content', 'Content'), ('ae', 'Application Engineer')], default='content', max_length=20),
        ),
        migrations.AlterField(
            model_name='entryitem',
            name='plan_item',
            field=models.ForeignKey(blank=True, help_text='Plan task this update row refers to (updates only).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='update_lines', to='tracker.entryitem'),
        ),
        migrations.CreateModel(
            name='WeeklyUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_start', models.DateField(help_text='Saturday that starts this week cycle')),
                ('setter_enhancements', models.PositiveIntegerField(default=0)),
                ('he_support_replies', models.PositiveIntegerField(default=0, verbose_name='#he_support_v2 Replies/Resolutions')),
                ('eng_assessment_replies', models.PositiveIntegerField(default=0, verbose_name='#engineering_assessment Replies/Resolutions')),
                ('facecode_replies', models.PositiveIntegerField(default=0, verbose_name='#engineering_facecode Replies/Resolutions')),
                ('data_requests_replies', models.PositiveIntegerField(default=0, verbose_name='#data_requests Replies/Resolutions')),
                ('redash_queries', models.PositiveIntegerField(default=0)),
                ('bug_fixes', models.PositiveIntegerField(default=0)),
                ('deployments', models.PositiveIntegerField(default=0)),
                ('setter_enhancements_count', models.PositiveIntegerField(default=0, verbose_name='Setter Enhancements (count)')),
                ('utilities', models.PositiveIntegerField(default=0)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='weekly_updates', to='tracker.member')),
            ],
            options={
                'ordering': ['-week_start', 'member__display_name'],
                'unique_together': {('member', 'week_start')},
            },
        ),
    ]
