# Generated by Django 3.2.7 on 2026-04-17 15:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0006_ae_role_and_weekly_update'),
    ]

    operations = [
        migrations.CreateModel(
            name='AEDailyUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_date', models.DateField()),
                ('setter_enhancements', models.PositiveIntegerField(default=0)),
                ('he_support_replies', models.PositiveIntegerField(default=0, verbose_name='#he_support_v2 Replies/Resolutions')),
                ('eng_assessment_replies', models.PositiveIntegerField(default=0, verbose_name='#engineering_assessment Replies/Resolutions')),
                ('facecode_replies', models.PositiveIntegerField(default=0, verbose_name='#engineering_facecode Replies/Resolutions')),
                ('data_requests_replies', models.PositiveIntegerField(default=0, verbose_name='#data_requests Replies/Resolutions')),
                ('redash_queries', models.PositiveIntegerField(default=0)),
                ('bug_fixes', models.PositiveIntegerField(default=0)),
                ('deployments', models.PositiveIntegerField(default=0)),
                ('setter_enhancements_count', models.PositiveIntegerField(default=0, verbose_name='Setter Enhancements (count)')),
                ('utilities', models.PositiveIntegerField(default=0)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ae_daily_updates', to='tracker.member')),
            ],
            options={
                'ordering': ['-entry_date', 'member__display_name'],
            },
        ),
        migrations.DeleteModel(
            name='WeeklyUpdate',
        ),
        migrations.AddIndex(
            model_name='aedailyupdate',
            index=models.Index(fields=['entry_date'], name='tracker_aed_entry_d_7dd163_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='aedailyupdate',
            unique_together={('member', 'entry_date')},
        ),
    ]
